
version: "3"
services:
  reverseproxy:
    build:
      context: reverse-proxy
    image: abhimanyudwivedi/udagram-rp
  api_user:
    build:
      context: udagram-api-user
    image: abhimanyudwivedi/udagram-api-user
  api_feed:
    build:
      context: udagram-api-feed
    image: abhimanyudwivedi/udagram-api-feed
  frontend:
    build:
      context: udagram-frontend
    image: abhimanyudwivedi/udagram-frontend