apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      app: reverseproxy

  template:
    metadata:
      labels:
        app: reverseproxy

    spec:
      containers:
        - name: reverseproxy

          image: abhimanyudwivedi/udagram-rp
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080