apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 8100
      targetPort: 80
  selector:
    service: udagram-frontend